package com.dalton.myleavemanager.database.room

import com.dalton.myleavemanager.database.room.entities.LeaveRecordEntity

val predefinedLeaveRecords = listOf(
    LeaveRecordEntity(
        id = 1,
        employeeId = 101,
        department = "HR",
        leaveDays = 5,
        leaveHours = 0,
        employeeName = "Alice Johnson",
        leaveType = "Annual Leave",
        startDate = "2021-06-10",
        endDate = "2021-06-15",
        reason = "Family Vacation",
        additionalNotes = "",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 2,
        employeeId = 102,
        department = "Finance",
        leaveDays = 3,
        leaveHours = 0,
        employeeName = "Bob Smith",
        leaveType = "Sick Leave",
        startDate = "2022-02-15",
        endDate = "2022-02-18",
        reason = "Health Recovery",
        additionalNotes = "Doctor's Note Provided",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 3,
        employeeId = 103,
        department = "Engineering",
        leaveDays = 7,
        leaveHours = 0,
        employeeName = "Charlie Brown",
        leaveType = "Annual Leave",
        startDate = "2021-12-20",
        endDate = "2021-12-27",
        reason = "Holiday Vacation",
        additionalNotes = "Visiting Family Abroad",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 4,
        employeeId = 104,
        department = "Marketing",
        leaveDays = 2,
        leaveHours = 0,
        employeeName = "Diana Prince",
        leaveType = "Personal Leave",
        startDate = "2023-01-15",
        endDate = "2023-01-17",
        reason = "Personal Errands",
        additionalNotes = "",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 5,
        employeeId = 105,
        department = "IT",
        leaveDays = 10,
        leaveHours = 0,
        employeeName = "Edward Norton",
        leaveType = "Annual Leave",
        startDate = "2022-07-01",
        endDate = "2022-07-11",
        reason = "Summer Vacation",
        additionalNotes = "",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 6,
        employeeId = 106,
        department = "Operations",
        leaveDays = 4,
        leaveHours = 0,
        employeeName = "Fiona Carter",
        leaveType = "Sick Leave",
        startDate = "2023-05-10",
        endDate = "2023-05-14",
        reason = "Medical Leave",
        additionalNotes = "Hospitalized",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 7,
        employeeId = 107,
        department = "Finance",
        leaveDays = 6,
        leaveHours = 0,
        employeeName = "George Michaels",
        leaveType = "Annual Leave",
        startDate = "2022-11-01",
        endDate = "2022-11-07",
        reason = "Family Reunion",
        additionalNotes = "",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 8,
        employeeId = 108,
        department = "HR",
        leaveDays = 3,
        leaveHours = 0,
        employeeName = "Helen Grace",
        leaveType = "Maternity Leave",
        startDate = "2021-03-01",
        endDate = "2021-03-04",
        reason = "Postnatal Care",
        additionalNotes = "Partial Leave",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 9,
        employeeId = 109,
        department = "Engineering",
        leaveDays = 1,
        leaveHours = 0,
        employeeName = "Isaac Newton",
        leaveType = "Emergency Leave",
        startDate = "2023-07-15",
        endDate = "2023-07-15",
        reason = "Urgent Family Matter",
        additionalNotes = "",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 10,
        employeeId = 110,
        department = "Operations",
        leaveDays = 2,
        leaveHours = 0,
        employeeName = "Jack Ryan",
        leaveType = "Sick Leave",
        startDate = "2022-04-10",
        endDate = "2022-04-12",
        reason = "Flu",
        additionalNotes = "Work from Home After Recovery",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 11,
        employeeId = 111,
        department = "IT",
        leaveDays = 5,
        leaveHours = 0,
        employeeName = "Kelly Clarkson",
        leaveType = "Annual Leave",
        startDate = "2023-09-20",
        endDate = "2023-09-25",
        reason = "Vacation",
        additionalNotes = "",
        status = "Approved"
    ),
    LeaveRecordEntity(
        id = 12,
        employeeId = 112,
        department = "Marketing",
        leaveDays = 4,
        leaveHours = 0,
        employeeName = "Laura Bush",
        leaveType = "Personal Leave",
        startDate = "2021-08-10",
        endDate = "2021-08-14",
        reason = "Family Events",
        additionalNotes = "",
        status = "Approved"
    )
)
